name: 'Clean WS Action'
description: 'Cleans up the workspace before and after the job'
author: 'fthdgn'
branding:
  icon: 'delete'
  color: 'red'
inputs:
  keepGit:
    description: 'Keep the .git folder to speedup cloning'
    required: false
runs:
  using: 'node12'
  main: 'cleanup.js'
  post: 'cleanup.js'
